default:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_BIGQUERY_PROJECT', 'big-star-collections-501913') }}" 
      
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET', 'big_star_collections_501913') }}" 
      
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE', 'C:/Users/pramod makwana/Desktop/end-to-end-data-engineering-project-4413618/big-star-collections-501913-05e3846c3337.json') }}"
      location: "{{ env_var('DBT_BIGQUERY_LOCATION', 'US') }}"
      priority: interactive
      threads: 1
      job_execution_timeout: 300
      job_retries: 1
  target: dev